### ISSUE TITLE
PaGMOEx main Undefined reference to boost

### ISSUE THREAD

**Issue by mvandenbroeck** [Tudat/tudatExampleApplications#12]
Hi,

I copied
`tudatExampleApplications/libraryExamples/PaGMOEx/main.cpp`
and
`tudatExampleApplications/libraryExamples/PaGMOEx/Problems`
into my personal Thesis folder located directly in `tudatBundle/Thesis`. I added the PaGMO related statements in `tudatBundle/Thesis/CMakeLists.txt` and added the `FindPaGMO.cmake` to the `tudatBundle/Thesis/CMakeModules`.
When compiling `tudatBundle/Thesis/mainOptimizationExample.cpp` (renamed from `main.cpp`, but the code is identical to `tudatExampleApplications/libraryExamples/PaGMOEx/main.cpp`), I get compile errors of the following type:

C:\tudatBundle_mvdb\pagmo\src\algorithm\jde.cpp: -1: error: undefined reference to '_imp___ZN5boost7archive6detail17basic_oserializerD2Ev'

The full compile output can be found [here](https://github.com/Tudat/tudatExampleApplications/files/794276/Compile_output_1.txt).

What is the cause of these errors and how can I resolve them?

Thanks,

Michael

**Comment by magnific0** [comment]
@mvandenbroeck can you post your CMakeLists.txt of your project here? Also let me know whether PaGMOEx is building correctly in its own environment.

The problem is that the linking the boost libraries is going wrong. 

If I have to guess: I think you're not "finding" all the necessary boost libraries in your ```find_package(boost)``` command. PaGMO requires additional libraries, such as serialization.

Cheers!

**Comment by mvandenbroeck** [comment]
Hi,

Here is the [CMakeLists.txt](https://github.com/Tudat/tudatExampleApplications/files/796134/CMakeLists.txt) of my Thesis project.

Thanks,

Michael

**Comment by mvandenbroeck** [comment]
In case you also need the tudatBundle/CMakeLists.txt.
[Here](https://github.com/Tudat/tudatExampleApplications/files/797069/CMakeLists.txt) it is.

Cheers,

Michael

**Comment by magnific0** [comment]
@mvandenbroeck thanks! I am quite sure I replied here earlier today, but it seems my message didn't get posted, strange... 

1. Could you let me know whether PaGMOEx is building properly in its own environment?
2. Your project's CMakeLists.txt looks good to me, but perhaps you can try and change the order in which libraries are linked to your application in ```target_link_libraries```. This can make a difference, although I'm not convinced it will in this case.
3. Why is USE_PAGMO OFF in your top-level CMakeLists.txt?

Thanks!

**Comment by mvandenbroeck** [comment]
Hi Jacco,

1. When building PaGMOEx main in its own environment, I get thousands of warnings, but no errors. Most of the warnings have the following form:
`typedef 'boost_concept_checkXXX' locally defined but not used [-Wunused-local-typedefs]`.
The entire compile output is 
[Compile_output_2.txt](https://github.com/Tudat/tudatExampleApplications/files/797249/Compile_output_2.txt).
2. When playing around with the order in which the libraries are linked to my application, I still get the boost serialization errors. The compile output is similar to what it was before: 
[Compile_output_3.txt](https://github.com/Tudat/tudatExampleApplications/files/797270/Compile_output_3.txt)

3. That's a good point. I forgot to put it on ON. This didn't change anything though. Isn't this strange?

Cheers

**Comment by magnific0** [comment]
@mvandenbroeck thanks for the quick follow up. Regarding (1) this means that the problem is most likely in the CMakeLists.txt, although I wouldn't know where, since the obvious candidates look okay to me. Re (3) Maybe, but if it was on before, it at least forced add_boost to compile the correct libraries. After that it's not really important any more.

My approach from here would be to start of with an (almost) exact replica of PaGMOEx/CMakeLists.txt (such that it builds) and slowly add in all additional components in your CMakeLists.txt until it fails and pinpoint the problem that way. 

We can look at it together if you want, but I'm afraid I don't have time until late next week.

**Comment by mvandenbroeck** [comment]
Hi Jacco,

I will try the approach you mentioned and contact you if it keeps failing. The only thing is that the compiling process of the `PaGMOEx/CMakeListst.txt` is very slow because of all the warnings, but I can probably suppress them.

Thanks for your help and time,

Michael

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
